server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/authdb}
    username: ${DB_USERNAME:authuser}
    password: ${DB_PASSWORD:authpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    secret: ${JWT_SECRET:ZmFrZV9zZWNyZXRfZmFrZV9zZWNyZXRfZmFrZV9zZWNyZXRf}
    expirationSeconds: ${JWT_EXPIRATION_SECONDS:3600}



